### ISSUE TITLE
Add step "npm install" to website

### ISSUE THREAD

**Issue by Correct-Syntax** [jeffreyvr/tailpress#58] opened 2021-09-15 14:40 UTC
The step where you need to run ``npm install`` seems to be missing from the website. This is "obvious" for those that know how npm works, but could be troublesome for beginners, etc.

Between step 2 and 3 you have to run ``npm install``  otherwise an error occurs. It doesn't seem that step 2 or 3 covers this.

![Screenshot 2021-09-15 093614](https://user-images.githubusercontent.com/60711001/133454231-3aba2642-9d42-4244-a20d-d8f947f93e1a.png)

**Comment by jeffreyvr** [comment] 2021-09-15 15:19
The installer already runs `npm install` for you. That's why that step is not listed on the site. See:

https://github.com/jeffreyvr/tailpress-installer/blob/master/src/Console/NewCommand.php#L70

**Comment by Correct-Syntax** [comment] 2021-09-15 15:30
@jeffreyvr okay, I had the thought that maybe the installer was *supposed* to install the packages. 

Here's what happened (this is repeatable):

Select No when it asks to install wordpress also.

```
> npm run watch

> tailpress@2.0.0 watch
> cross-env NODE_ENV=development concurrently "npm run watch:css-app" "npm run watch:css-editor" 
"npm run watch:js"

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
```

(I thought that it was because the packages were not installed that the installer may not do it since I didn't see the ``install`` command there). I then ran ``npm install`` and the ``watch`` command worked after that.

**Comment by jeffreyvr** [comment] 2021-09-16 09:58
Thanks for your response @Correct-Syntax! I can't reproduce this from my end unfortunately. I have followed the steps as you described but I don't run into that error.

**Comment by jeffreyvr** [comment] 2021-09-17 12:49
https://user-images.githubusercontent.com/9550079/133784740-21aeb885-1ecc-46ec-8068-1103cf38955f.mov

In the above video you can see I don't have this issue when I follow the steps as you mentioned. Will close this issue for now.

**Closed by jeffreyvr** 2021-09-17 12:49 UTC
