### ISSUE TITLE
Margin issue with wide width cover block

### ISSUE THREAD

**Issue by samalexander** [jeffreyvr/tailpress#92] opened 2022-02-24 14:30 UTC
Hi. First off, thanks for your awesome work on this starter theme! I have run into a minor issue that I hope you can help with.

When adding a cover Gutenberg block to your page and setting the alignment to 'wide width', the block's alignment is messed up on the front end:

![Screenshot 2022-02-24 at 14 18 30](https://user-images.githubusercontent.com/935782/155541551-a35a6f9d-ffbd-4ecb-9c81-9481f0706b34.png)

The only way to resolve seems to be to override the `-mx-16` class that your plugin applies to `.alignwide` with something like `mx-auto` but this obviously prevents the block stretching past the bounds of the container.

**Comment by maxleistner** [comment] 2022-03-06 11:47
I think the problem is, that side-wide should have a max-width of 1410px instead of 1280px, because the default width is already 1280px. Therefore side-wide would be the same width as default, but cause of the negative margin-left it is misplaced.

**Comment by jeffreyvr** [comment] 2022-03-07 16:45
You were right @maxleistner. This is fixed in the master branch. Thanks for reporting the issue @samalexander!

**Closed by jeffreyvr** 2022-03-07 16:45 UTC
