### ISSUE TITLE
Upgrading to Tailwind CSS 2.2.0 causes infinite loop when watching for changes

### ISSUE THREAD

**Issue by dapunkt** [jeffreyvr/tailpress#32] opened 2021-06-18 09:51 UTC
When I now 'npm run watch', i get an infinite loop, any idea what is changed?

**Comment by jeffreyvr** [comment] 2021-06-18 10:00
Upgrading to Tailwind CSS 2.2.0 seems to be causing an infinite loop when running `npx mix watch` / `npm run watch`. 

Not yet sure why this is yet.

**Comment by danieledistanio** [comment] 2021-06-18 11:06
FYI it is happening to me as well with a different theme/setup.

**Comment by jeffreyvr** [comment] 2021-06-18 11:06
Thanks @danieledistanio. I've just created an issue at the Tailwind CSS repository. https://github.com/tailwindlabs/tailwindcss/issues/4691

**Comment by danieledistanio** [comment] 2021-06-18 14:51
Adam replied, in my case the issue is having:

'./*.php'

in the purge list, removing that fixes it.

**Comment by jeffreyvr** [comment] 2021-06-18 14:53
@danieledistanio Jep, that resolves it for me too. Moving to Tailwind CSS 2.2.0 we probably need to be more specific with our purge css options.

**Comment by jeffreyvr** [comment] 2021-06-18 15:02
Fixed by a more specific purge configuration in TailPress 0.1.1..

**Closed by jeffreyvr** 2021-06-18 15:02 UTC
