### ISSUE TITLE
Error with npm run development

### ISSUE THREAD

**Issue by mangomkt** [jeffreyvr/tailpress#9] opened 2021-02-03 17:06 UTC
I get the following error when I try to run `npm run development`

`[webpack-cli] [Error: EINVAL: invalid argument, mkdir 'C:\github\tailpress\C:'] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'mkdir',
  path: 'C:\\github\\tailpress\\C:'
}
npm ERR! code 2
npm ERR! path C:\github\tailpress
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c webpack --progress --config=C:\\github\\tailpress\\node_modules\\laravel-mix\\setup\\webpack.config.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cg\AppData\Local\npm-cache\_logs\2021-02-03T17_05_30_180Z-debug.log
npm ERR! code 2
npm ERR! path C:\github\tailpress
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c mix

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cg\AppData\Local\npm-cache\_logs\2021-02-03T17_05_30_373Z-debug.log`

**Comment by jeffreyvr** [comment] 2021-02-04 11:26
A similar error issue has been opened at the Laravel Mix repository https://github.com/JeffreyWay/laravel-mix/issues/2587

A quick [Google search](https://www.google.com/?q=Error:+EINVAL:+invalid+argument,+mkdir) results in quite some possible related forum topics.

Perhaps you can take a look. I don't think this error is directly related to TailPress but more to Node.

**Comment by dezareo** [comment] 2021-02-07 14:06
Hello Jeffrey, I've got similar issue as @mangomkt 

 yarn run dev
yarn run v1.0.2
(node:7836) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
$ mix
[webpack-cli] [Error: EINVAL: invalid argument, mkdir 'C:\laragon\www\tailpress\wp-content\themes\tailpress\C:'] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'mkdir',
  path: 'C:\\laragon\\www\\tailpress\\wp-content\\themes\\tailpress\\C:'
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Please can you explore this issue and help us resolve this problem. I try to go Jeffrey Way topic but there is no specific answer that resolve this issue.

tnx

**Comment by jeffreyvr** [comment] 2021-02-08 10:07
Unfortunately I don't have any machine running on Windows so can't really test it out. Did you find anything through the Google search @dezareo?

**Comment by dezareo** [comment] 2021-02-08 14:41
@mangomkt Are you find solution for npm run dev issue?

**Comment by dezareo** [comment] 2021-02-08 15:19
> Unfortunately I don't have any machine running on Windows so can't really test it out. Did you find anything through the Google search @dezareo?
> 
> Maybe take a look at this issue which appears to look a lot like the error you are having [JeffreyWay/laravel-mix#1687 (comment)](https://github.com/JeffreyWay/laravel-mix/issues/1687#issuecomment-398169126)
> 
> I don't think this issue is related directly to TailPress but more to Node.

Unfortunately, I hard struggle to resolve this problem for two days. There is no solution on the internet for this. Can you install Win 10 on Virtual Machine and test your code? Can you ask some friend of you, colleague to test your code on Windows. It's pretty shameful, but I'm very close to give up and forget your project. But, I said before, pretty good WordPress theme, unique.

**Comment by jeffreyvr** [comment] 2021-02-08 15:37
@dezareo Did you try the to remove the `node_modules` folder and the `package-lock.json` and `yarn.lock` files? Then run the installation commands again.

**Comment by dezareo** [comment] 2021-02-08 16:07
Yes, several times. I tried with npm and also with yarn. Same problem. 

This is logfile. Whole process break at 95% 

0 verbose cli [
0 verbose cli   'C:\\laragon\\bin\\nodejs\\node-v14\\node.exe',
0 verbose cli   'C:\\Users\\dez\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'dev'
0 verbose cli ]
1 info using npm@7.5.2
2 info using node@v14.15.4
3 timing config:load:defaults Completed in 4ms
4 timing config:load:file:C:\Users\dez\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 5ms
5 timing config:load:builtin Completed in 5ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 2ms
8 timing config:load:file:C:\laragon\www\tailpress\wp-content\themes\tailpress\.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:C:\Users\dez\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\dez\AppData\Roaming\npm\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 3ms
18 timing config:load Completed in 23ms
19 verbose npm-session 7c2a198e75011567
20 timing npm:load Completed in 49ms
21 timing command:run-script Completed in 42879ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Users\dez\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose pkgid tailpress@0.0.5
24 verbose cwd C:\laragon\www\tailpress\wp-content\themes\tailpress
25 verbose Windows_NT 10.0.18363
26 verbose argv "C:\\laragon\\bin\\nodejs\\node-v14\\node.exe" "C:\\Users\\dez\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
27 verbose node v14.15.4
28 verbose npm  v7.5.2
29 error code 2
30 error path C:\laragon\www\tailpress\wp-content\themes\tailpress
31 error command failed
32 error command C:\WINDOWS\system32\cmd.exe /d /s /c mix
33 verbose exit 2

**Comment by jeffreyvr** [comment] 2021-02-08 17:42
@dezareo Just did an update after testing on Windows. Ran into the original error of this issue and seems to be fixed now. 

Could you clone the repository again and see if it works now?

**Comment by dezareo** [comment] 2021-02-08 18:18
:) I just wanna say Jeffrey you are the man. Great job. The problem is solved. Thanks for the fast response. Can wait your tutorial on YT. 

Best regards,
Dragan

**Comment by jeffreyvr** [comment] 2021-02-08 18:35
Thanks @dezareo!

**Closed by jeffreyvr** 2021-02-08 18:35 UTC

**Comment by mangomkt** [comment] 2021-02-10 02:33
@jeffreyvr You da man!
